from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.support.ui import Select
import time

driver = webdriver.Chrome(executable_path=r"C:\Users\mushtaq.hussain\PycharmProjects\Selenium\driver\chromedriver.exe")
driver.maximize_window()
driver.get("https://www.ounass.ae/")
time.sleep(2)
driver.find_element_by_id("onesignal-slidedown-cancel-button").click()
time.sleep(2)
action = ActionChains(driver)
firstLevelMenu = driver.find_element_by_class_name("Popup-iconText")
action.move_to_element(firstLevelMenu).perform()
time.sleep(2)
loginButton = driver.find_element_by_xpath("//button[contains(text(),'Log In')]")
action.move_to_element(loginButton).click().perform()
email = driver.find_element_by_class_name("SignInForm-email")
email.send_keys("majid.rafique89@gmail.com")
password = driver.find_element_by_class_name("PasswordField-password")
password.send_keys("majid@123")
time.sleep(2)
loginButton = driver.find_element_by_xpath("//button[contains(text(),'Log In')]")
loginButton.click()
time.sleep(2)
driver.find_element_by_class_name("Popup-iconText").click()
emailField = driver.find_element_by_class_name("MyAccountPage-link")
emailField.click()
time.sleep(2)
disableEmail = driver.find_element_by_name("email")
disableEmail.is_enabled()
print ("Email field id found disabled")
VerifyEamil = driver.find_element_by_name("email")
emailText = VerifyEamil.get_attribute("value")
# print(emailText)
assert emailText == "majid.rafique89@gmail.com (Not editable)"
print("Email field has been verified")
time.sleep(2)
addressBook= driver.find_elements_by_xpath("//span[contains(text(),'My Address Book')]")
addressBook.click()
editbtn = driver.find_elements_by_xpath("//button[contains(text(),'Edit')]")
editbtn.click()
selectElement = driver.find_element_by_class_name("Select-value")
selectElement.send_keys("+971")
selectElement = driver.switch_to.active_element
# select_country_code = Select(selectElement)
# selectElement.select_by_visible_text("+971")
time.sleep(2)
PhoneField = driver.find_element_by_id("mobileNumber")
PhoneField.send_keys("67324238")
updateBtn = driver.find_elements_by_xpath("//button[contains(text(),'Update Address')]")
updateBtn.click()
time.sleep(2)
msg = driver.find_elements_by_xpath("//p[contains(text(),'Your address is successfully updated')]")
assert msg.text == "Your address is successfully updated"
driver.close()
driver.quit()